
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: proyect_backend
  username: postgres
  password: root

  
test:
  <<: *default
  database: proyect_backend_test
  username: postgres
  password: root


production:
  <<: *default
  database: proyect_backend_production
  username: postgres
  password: <%= ENV["PROYECT_BACKEND_DATABASE_PASSWORD"] %>
